on: release
name: Deploy on Release
jobs:
  gitHubActionForNpm:
    name: GitHub Action for npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for npm
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        entrypoint: npm
        args: ci
    - name: 'Build '
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        entrypoint: npm
        args: run build
    - name: markuseckstein/github_actions/ftp-deploy@master
      uses: markuseckstein/github_actions/ftp-deploy@master
      env:
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        LOCAL_DIR: ${{ secrets.LOCAL_DIR }}
        REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
